config/routes.rb
Rails.application.routes.draw do
  root 'auctions#index'
  devise_for :users
  resources :auctions, only: [:index] do
    resources :bids, only: [:index, :new, :create]
  end

  resources :makers, only: [] do
    resources :cars, only: :index
  end

  namespace :my do
    resources :auctions, except: [:show] do
      resources :bids, only: [:index, :edit, :update]
    end
  end
end

app/models/auction.rb
# == Schema Information
#
# Table name: auctions
#
#  id            :bigint(8)        not null, primary key
#  user_id       :bigint(8)
#  close_at      :datetime         not null
#  closed        :boolean          default(FALSE)
#  title         :string(255)      not null
#  description   :text(65535)      not null
#  initial_price :integer          default(0)
#  maker_id      :bigint(8)
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  car_id        :bigint(8)
#

class Auction < ApplicationRecord
  is_impressionable
  attribute :default_close_time, :datetime, default: -> { DateTime.now + 1.week }

  belongs_to :user
  belongs_to :maker
  belongs_to :car

  delegate :cars, to: :maker

  has_many :bids, dependent: :destroy
  # オークションにビッドしたユーザー（注：重複しうる）
  has_many :bidders, through: :bids, source: :user

  validates :close_at, presence: true
  validates :user_id, presence: true
  validates :maker_id, presence: true
  validates :car_id, presence: true
  validates :title, presence: true
  validates :description, presence: true
  validates :close_at, presence: true
  validates :initial_price, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0}

  validate :close_at_must_be_future, on: :create
  validate :car_must_have_relationship_with_maker
  validate :size_limit_ongoing_auctions, on: :create

  scope :ongoing, -> {
    includes(:maker, :car).where(closed: false)
        .order(created_at: :desc)
  }

  scope :must_be_closed, -> {
    includes(:maker, :car, :user)
        .where('close_at <= ? AND closed = ?', DateTime.now, false)
  }

  def min_price
    if bidden?
      bids.minimum(:price)
    else
      initial_price
    end
  end

  def my_auction?(current_user)
    return false if current_user.nil?
    user_id == current_user.id ? true : false
  end

  def bidden?
    bidders.exists?
  end

  def accept_and_close
    if cheapest_bid = bids.includes(:user).last
      cheapest_bid.update!(accepted: true)
    end
    self.update!(closed: true)
  end

  private

  def close_at_must_be_future
    if close_at <= Time.now
      errors.add(:close_at, 'は現在以降の日時を設定してください')
    end
  end

  def car_must_have_relationship_with_maker
    return if car_id.nil?
    car = Car.find_by(id: car_id)
    unless cars.include?(car)
      errors.add(:car_id, 'が選択したメーカーにはラインナップされていません。')
    end
  end

  def size_limit_ongoing_auctions
    limit_size = 3
    if user.owning_auctions.where(closed: false).size >= limit_size
      errors.add(:user_id, "1人につき開催できるオークションは最大#{limit_size}つまでです。")
    end
  end
end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
  def index
    @q = Auction.ongoing.includes(:car, :maker, :user).ransack(params[:q])
    @auctions = @q.result
  end
end

app/controllers/my/application_controller.rb
class My::ApplicationController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/my/auctions_controller.rb
class My::AuctionsController < My::ApplicationController
  before_action :set_auction, only: [:edit, :update, :destroy]

  def index
    @auctions = current_user.owning_auctions
  end

  def new
    @auction = current_user.owning_auctions.new
  end

  def edit
  end

  def create
    @auction = current_user.owning_auctions.new(auction_params)

    respond_to do |format|
      if @auction.save
        format.html {redirect_to [:my, :auctions], notice: 'オークションが作成されました。'}
      else
        format.html {render :new}
      end
    end
  end

  def update
    respond_to do |format|
      if @auction.update(auction_params)
        format.html {redirect_to [:my, :auctions], notice: 'オークションが更新されました。'}
      else
        format.html {render :edit}
      end
    end
  end

  def destroy
    @auction.destroy
    respond_to do |format|
      format.html {redirect_to my_auctions_url, notice: 'オークションが削除されました。'}
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_auction
    @auction = Auction.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def auction_params
    params.require(:auction).permit(:close_at,
                                    :closed,
                                    :title,
                                    :description,
                                    :initial_price,
                                    :user_id,
                                    :maker_id,
                                    :car_id)
  end
end

app/controllers/my/bids_controller.rb
class My::BidsController < My::ApplicationController
  before_action :set_auction, :others_auction?
  before_action :set_bid, only: [:edit, :update]

  def index
    @bids = @auction.bids.asc_price
  end

  def edit
    if @bid.auction.closed?
      redirect_to [:my, :auction, :bids], notice: '既にオークションは終了しています。'
    end
  end

  def update
    respond_to do |format|
      if @bid.update!(bid_params) && @auction.update!(closed: true)
        format.html {redirect_to [:my, :auction, :bids], notice: '購入しました'}
      else
        format.html {render :edit}
      end
    end
  end

  private
  def set_auction
    @auction = Auction.find(params[:auction_id])
  end

  def others_auction?
    unless @auction.user.id == current_user.id
      redirect_to root_path, notice: '権限がありません'
    end
  end

  def set_bid
    @bid = Bid.find(params[:id])
  end

  def bid_params
    params.require(:bid).permit(:accepted)
  end
end

app/helpers/auctions_helper.rb
module AuctionsHelper
end

app/helpers/my/auctions_helper.rb
module My::AuctionsHelper
  def mention_status(closed)
    closed ? '終了' : '開催中'
  end
end

app/views/my/auctions/_form.html.slim
- breadcrumb :my_auction, [:my, @auction]
= simple_form_for(@auction, url: [:my, @auction]) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-controls
    - if controller.action_name =~ /new|create/
      = f.input :user_id, as: :hidden
      = f.input :maker_id, as: :select, collection: Maker.all
      = f.input :car_id, as: :select, collection: Car.all
      = f.input :initial_price
      .datetime-inputs
        = f.input :close_at, default: @auction.default_close_time
    = f.input :title
    = f.input :description, input_html: {rows: 10}
    = f.button :submit, class: 'btn btn-primary btn-block'

app/views/my/auctions/edit.html.slim
h2 オークション編集

== render 'form'

=> link_to 'Show', my_auction_path(@auction)
'|
=< link_to 'Back', my_auctions_path

app/views/my/auctions/index.html.slim
= link_to '新規オークション作成', new_my_auction_path, class: 'btn btn-block btn-primary'
br
h2
  | マイオークション一覧

- @auctions.each do |auction|
  .card
    .card-header.d-inline-block
      = "#{auction.title}（#{mention_status(auction.closed)}）"
      span.float-right
        = link_to my_auction_bids_path(auction), data: {"turbolinks" => false} do
          i.fas.fa-gavel.mr-3 data-placement="top" data-toggle="tooltip" title=("入札一覧／購入")
        end
        = link_to edit_my_auction_path(auction), data: {"turbolinks" => false} do
          i.fas.fa-edit.mr-3 data-placement="top" data-toggle="tooltip" title=("編集")
        end
        = link_to my_auction_url(auction), data: { confirm: '削除しますか？' }, method: :delete do
          i.far.fa-trash-alt data-placement="top" data-toggle="tooltip" title=("削除")
        end
    .card-body
      p.card-text
        = "ターゲット：#{auction.maker.name} #{auction.car.name}"
  br

app/views/my/auctions/new.html.slim
h2 新規オークション

== render 'form'

= link_to 'Back', my_auctions_path