config/routes.rb
Rails.application.routes.draw do
  root 'auctions#index'
  devise_for :users
  resources :auctions, only: [:index] do
    resources :bids, only: [:index, :new, :create]
  end

  resources :makers, only: [] do
    resources :cars, only: :index
  end

  namespace :my do
    resources :auctions, except: [:show] do
      resources :bids, only: [:index, :edit, :update]
    end
  end
end

app/models/bid.rb
# == Schema Information
#
# Table name: bids
#
#  id         :bigint(8)        not null, primary key
#  price      :integer
#  suggestion :text(65535)
#  image      :string(255)
#  user_id    :bigint(8)
#  auction_id :bigint(8)
#  accepted   :boolean          default(FALSE)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Bid < ApplicationRecord
  mount_uploader :image, ImageUploader

  validates :suggestion, presence: true
  validates :price, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0}

  validate :new_price_must_be_lowest, on: :create
  validate :bidder_must_not_be_auction_master, on: :create
  validate :auction_must_be_open

  belongs_to :user
  belongs_to :auction

  scope :asc_price, -> {
    includes(:user).order(:price)
  }

  private

  def new_price_must_be_lowest
    return if price.nil?
    # where.notは画面から入力したレコードをはねるための処置
    min_price = auction.bids.where.not(id: nil).minimum(:price) || auction.initial_price
    if price >= min_price
      errors.add(:price, "は 「#{min_price}」より低い額を入力してください。")
    end
  end

  def bidder_must_not_be_auction_master
    bidder = user
    auction_master = auction.user
    if (bidder == auction_master)
      errors.add(:user, "は、自分のオークションには入札できません。")
    end
  end

  def auction_must_be_open
    if auction.closed?
      errors.add(:auction, "は、既に終了しているため、入札できません")
    end
  end
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  before_action :set_auction, :my_auction?

  def index
    @bids = @auction.bids.asc_price
    impressionist(@auction, nil, unique: [:session_hash])
  end

  def new
    @bid = @auction.bids.new
  end

  def create
    @bid = @auction.bids.new(bid_params)
    @bid.user_id = current_user.id

    respond_to do |format|
      if @bid.save
        format.html do redirect_to auction_bids_url, notice: '新規入札が登録されました'
        end
      else
        format.html { render :new }
      end
    end
  end

  private
    def set_auction
      @auction = Auction.find(params[:auction_id])
    end

    def my_auction?
      if @auction.user.id == current_user.id
        redirect_to root_path, notice: '権限がありません'
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bid_params
      params.require(:bid).permit(:price,
                                  :suggestion,
                                  :image,
                                  :image_cache,
                                  :auction_id)
    end
end

app/controllers/my/bids_controller.rb
class My::BidsController < My::ApplicationController
  before_action :set_auction, :others_auction?
  before_action :set_bid, only: [:edit, :update]

  def index
    @bids = @auction.bids.asc_price
  end

  def edit
    if @bid.auction.closed?
      redirect_to [:my, :auction, :bids], notice: '既にオークションは終了しています。'
    end
  end

  def update
    respond_to do |format|
      if @bid.update!(bid_params) && @auction.update!(closed: true)
        format.html {redirect_to [:my, :auction, :bids], notice: '購入しました'}
      else
        format.html {render :edit}
      end
    end
  end

  private
  def set_auction
    @auction = Auction.find(params[:auction_id])
  end

  def others_auction?
    unless @auction.user.id == current_user.id
      redirect_to root_path, notice: '権限がありません'
    end
  end

  def set_bid
    @bid = Bid.find(params[:id])
  end

  def bid_params
    params.require(:bid).permit(:accepted)
  end
end

app/helpers/bids_helper.rb
module BidsHelper
  def sold_label(accepted)
    if accepted
      content_tag(:p,'SOLD!', class: 'sold-label')
    end
  end
end

app/views/bids/_form.html.slim
= simple_form_for([@auction, @bid]) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-controls
    = f.input :price
    = f.input :suggestion, input_html: {rows: 10}
    = f.input :image, as: :file
    = f.input :image_cache, as: :hidden
    = f.button :submit, class: 'btn btn-primary btn-block'

app/views/bids/index.html.slim
- breadcrumb :bids, @auction

- if user_signed_in?
  = link_to '新規入札する', new_auction_bid_path, class: 'btn btn-block btn-primary'
  br
- else
  p = '入札する場合はログインしてください。'

h2
  | 入札一覧
- @bids.each do |bid|
  .card
    .card-header
      = "#{bid.user.name}からの提案"
    .card-body
      .d-flex.flex-wrap
        .order-1.p-6
          - if bid.image.present?
            = image_tag bid.image.thumbnail.url, class: 'thumbnail'
          - else
            = image_tag 'no_image.png', size: '200x150', class: 'thumbnail'
        .order-2.p-6
          p.card-text
            = "提示額：#{number_to_currency(bid.price)}"
          p.card-text
            = simple_format(h(bid.suggestion))
  br

app/views/bids/new.html.slim
- breadcrumb :bid, @bid

h2 新規入札

== render 'form'

= link_to 'Back', auction_bids_path