config/routes.rb
Rails.application.routes.draw do
  root 'auctions#index'
  devise_for :users
  resources :auctions, only: [:index] do
    resources :bids, only: [:index, :new, :create]
  end

  resources :makers, only: [] do
    resources :cars, only: :index
  end

  namespace :my do
    resources :auctions, except: [:show] do
      resources :bids, only: [:index, :edit, :update]
    end
  end
end

app/models/auction.rb
# == Schema Information
#
# Table name: auctions
#
#  id            :bigint(8)        not null, primary key
#  user_id       :bigint(8)
#  close_at      :datetime         not null
#  closed        :boolean          default(FALSE)
#  title         :string(255)      not null
#  description   :text(65535)      not null
#  initial_price :integer          default(0)
#  maker_id      :bigint(8)
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  car_id        :bigint(8)
#

class Auction < ApplicationRecord
  is_impressionable
  attribute :default_close_time, :datetime, default: -> { DateTime.now + 1.week }

  belongs_to :user
  belongs_to :maker
  belongs_to :car

  delegate :cars, to: :maker

  has_many :bids, dependent: :destroy
  # オークションにビッドしたユーザー（注：重複しうる）
  has_many :bidders, through: :bids, source: :user

  validates :close_at, presence: true
  validates :user_id, presence: true
  validates :maker_id, presence: true
  validates :car_id, presence: true
  validates :title, presence: true
  validates :description, presence: true
  validates :close_at, presence: true
  validates :initial_price, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0}

  validate :close_at_must_be_future, on: :create
  validate :car_must_have_relationship_with_maker
  validate :size_limit_ongoing_auctions, on: :create

  scope :ongoing, -> {
    includes(:maker, :car).where(closed: false)
        .order(created_at: :desc)
  }

  scope :must_be_closed, -> {
    includes(:maker, :car, :user)
        .where('close_at <= ? AND closed = ?', DateTime.now, false)
  }

  def min_price
    if bidden?
      bids.minimum(:price)
    else
      initial_price
    end
  end

  def my_auction?(current_user)
    return false if current_user.nil?
    user_id == current_user.id ? true : false
  end

  def bidden?
    bidders.exists?
  end

  def accept_and_close
    if cheapest_bid = bids.includes(:user).last
      cheapest_bid.update!(accepted: true)
    end
    self.update!(closed: true)
  end

  private

  def close_at_must_be_future
    if close_at <= Time.now
      errors.add(:close_at, 'は現在以降の日時を設定してください')
    end
  end

  def car_must_have_relationship_with_maker
    return if car_id.nil?
    car = Car.find_by(id: car_id)
    unless cars.include?(car)
      errors.add(:car_id, 'が選択したメーカーにはラインナップされていません。')
    end
  end

  def size_limit_ongoing_auctions
    limit_size = 3
    if user.owning_auctions.where(closed: false).size >= limit_size
      errors.add(:user_id, "1人につき開催できるオークションは最大#{limit_size}つまでです。")
    end
  end
end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
  def index
    @q = Auction.ongoing.includes(:car, :maker, :user).ransack(params[:q])
    @auctions = @q.result
  end
end

app/controllers/my/auctions_controller.rb
class My::AuctionsController < My::ApplicationController
  before_action :set_auction, only: [:edit, :update, :destroy]

  def index
    @auctions = current_user.owning_auctions
  end

  def new
    @auction = current_user.owning_auctions.new
  end

  def edit
  end

  def create
    @auction = current_user.owning_auctions.new(auction_params)

    respond_to do |format|
      if @auction.save
        format.html {redirect_to [:my, :auctions], notice: 'オークションが作成されました。'}
      else
        format.html {render :new}
      end
    end
  end

  def update
    respond_to do |format|
      if @auction.update(auction_params)
        format.html {redirect_to [:my, :auctions], notice: 'オークションが更新されました。'}
      else
        format.html {render :edit}
      end
    end
  end

  def destroy
    @auction.destroy
    respond_to do |format|
      format.html {redirect_to my_auctions_url, notice: 'オークションが削除されました。'}
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_auction
    @auction = Auction.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def auction_params
    params.require(:auction).permit(:close_at,
                                    :closed,
                                    :title,
                                    :description,
                                    :initial_price,
                                    :user_id,
                                    :maker_id,
                                    :car_id)
  end
end

app/helpers/auctions_helper.rb
module AuctionsHelper
end

app/helpers/my/auctions_helper.rb
module My::AuctionsHelper
  def mention_status(closed)
    closed ? '終了' : '開催中'
  end
end

app/views/auctions/_search.html.slim
.jumbotron
  h3
    | 検索
  = search_form_for(@q, url: root_path) do |f|
    .form-row
      = f.label :maker_id_in, 'メーカー：'
      = f.select :maker_id_in, Maker.all.map {|m| [m.name, m.id, data: {children_path: maker_cars_path(m)}]}, {include_blank: true}, class: 'select-parent'
    / = f.label :maker_id_in, 'メーカー：'
    / = f.collection_check_boxes :maker_id_in, Maker.all, :id, :name do |b|
    /   =< b.label { b.check_box + ' ' + b.text + '　'}

    - cars = @maker&.cars || []
    .form-row
      .form-inline.mr-2
        = f.label :car_id_in, '車名：'
        = f.select :car_id_in, cars.map {|c| [c.name, c.id]}, include_blank: true
      .form-inline.mr-2
        = f.label :title_cont, 'タイトル：'
        = f.search_field :title_cont, class: 'form-control-sm', placeholder: '文字で検索'
      .form-inline.mr-2
        = f.label :initial_price_lteq, '始値：'
        = f.number_field :initial_price_lteq, class: 'form-control-sm', placeholder: '指定値以下で検索'

    br
    = f.button '検索する', class: 'btn btn-block'

app/views/auctions/index.html.slim
h2
  | 開催中のオークション

= render 'search'
hr

- @auctions.each do |auction|
  .card
    .card-header.d-inline-block
      = auction.title
      span.float-right
        i.far.fa-eye.mr-3 = auction.impressionist_count
        - unless auction.my_auction?(current_user)
          = link_to auction_bids_path(auction), data: {"turbolinks" => false} do
            i.fas.fa-gavel data-placement="top" data-toggle="tooltip" title=("入札／入札一覧")
          end
    .card-body
      p.card-text
        = "開催者：#{auction.user.name}"
      p.card-text
        = "ターゲット：#{auction.maker.name} #{auction.car.name}"
      p.card-text
        = "始値：#{number_to_currency(auction.initial_price)}"
      - if auction.bidden?
        p.card-text
          = "最安入札額：#{number_to_currency(auction.min_price)}"
      - else
        p.card-text
          = "最安入札額：まだ入札がありません"
      p.card-text
        = "終了時間：#{l(auction.close_at, format: :long)}"
      p.card-text
        = simple_format(h(auction.description))
  br